name: Release
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --no-save
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun run commitlint --from=origin/main --to=HEAD
      - name: Validate code formatting
        run: |
          bun run format
          if [[ $(git status --porcelain) ]]; then
            echo "Code not properly formatted. Please run 'bun run format' locally and commit changes."
            exit 1
          fi
      - name: Lint & check types
        run: bun run check
      - name: Test
        run: bun test

  Release:
    needs: [Test]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: |
      github.ref == 'refs/heads/main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --no-save
      # - name: Install dependencies
      #   run: yarn install
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run semantic-release
